### PR TITLE
docs: fix typos in readme

### PR DESCRIPTION
**Pull request by S1SYPHOS**
Fixing typos, mostly .. great plugin!

### CODE REVIEW

**Comment by thathoff** [comment]
Hi, thanks for your pull request: Would you mind to update your commit message following the [Angular commit message conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)? In this case: `docs: fix typos in readme`. Thank you!

And yes: This projects lacks a contributing guide, I will create an issue for that! ;)

**Comment by S1SYPHOS** [comment]
There you go!
// Edit: I assume you meant the PR title?

**Comment by thathoff** [comment]
Hey, thanks for your update but I was talking about the commit message. So yours is `Update readme.md`. All other commits in this project follow the Angular convention so it would be great if your commit does that, too! ;-)

If you’re unsure how to change it: If this is the last commit in this branch (it should be) just run `git commit --amend -m "docs: fix typos in readme"` und `git push -f` (force because you’ve just modified a commit) afterwards.

Otherwise you need to run an interactive rebase. But that is not necessary I think.

**Comment by S1SYPHOS** [comment]
Was thinking you misspoke, gotta get back at this, right now I‘m afk

**Comment by S1SYPHOS** [comment]
Alright, now we're good to go. Won't happen again, kind Sir!

**Comment by thathoff** [comment]
Thank you very much!

**Comment by S1SYPHOS** [comment]
My pleasure

**Pull request merged**
